version: '3.7'

x-base-dev: &base-dev
  restart: on-failure
  volumes:
    - ./src:/src:rw
    - .:/project:rw

services:
  dev:
    <<: *base-dev
    build:
      context: .
      target: node_base
    working_dir: /src/wallboard/
    entrypoint: /usr/local/bin/yarn start
    ports:
      - "3000:3000"

  builder:
    <<: *base-dev
    build:
      context: .
      target: node_builder

  web_server:
    image: "salimfadhley/bigsmoke_web_site:latest"
    build:
      context: .
      target: web_server
    ports:
      - "80:80"
      - "8080:8080"





